version: '3.3'
services:

  API:
    image: 'gs-spring-boot-docker-0.1.0.jar'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update




  db:
    image: postgres:latest
    container_name: "stock-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=User
    ports:
      - "5632:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  testsdb:
    image: postgres
    container_name: "stock-postgres-test"
    ports:
      - "5633:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=User
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5