version: '3.3'
services:
  db:
    image: postgres
    container_name: "stock-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=User
    ports:
      - "5632:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  testsdb:
    image: postgres
    container_name: "stock-postgres"
    ports:
      - "5633:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=User
    volumes:
      - ./postgres-data:/var/lib/postgresql/data